import type { LucideIcon } from "lucide-react";
import {
  AlarmClock,
  Ambulance,
  Armchair,
  Backpack,
  BadgeCheck,
  BadgePlus,
  Balloon,
  Bath,
  Bell,
  BellRing,
  Bike,
  BriefcaseBusiness,
  BriefcaseMedical,
  Building2,
  BusFront,
  CakeSlice,
  CalendarDays,
  Camera,
  CarFront,
  Church,
  Clipboard,
  Cloud,
  CloudRain,
  CloudSun,
  Coins,
  Compass,
  Dumbbell,
  FileText,
  Flame,
  FlaskConical,
  Gamepad2,
  Ghost,
  Gift,
  Globe,
  GraduationCap,
  Grid2x2,
  Handbag,
  Headphones,
  Heart,
  Hotel,
  House,
  Image,
  Leaf,
  LibraryBig,
  LifeBuoy,
  ListTodo,
  Mail,
  Megaphone,
  Mic2,
  Monitor,
  Moon,
  MoonStar,
  Music,
  Music2,
  Package,
  Palette,
  Pill,
  Plane,
  Radio,
  Rocket,
  School,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Sofa,
  Soup,
  Sparkles,
  Speaker,
  Star,
  Stethoscope,
  Store,
  Sun,
  Syringe,
  Tent,
  TrainFront,
  TramFront,
  Trash2,
  TreePine,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  UserRound,
  Utensils,
  Video,
  Wallet,
  Watch,
  Waves,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";

type BrickIconEntry = {
  value: string;
  label: string;
  Icon: LucideIcon;
  aliases?: string[];
  legacyOnly?: boolean;
};

const brickIconEntries: BrickIconEntry[] = [
  { value: "grid-2x2", label: "Grid", Icon: Grid2x2, aliases: ["default", "layout-grid", "grid"] },
  { value: "sun", label: "Sun", Icon: Sun },
  { value: "cloud-sun", label: "Cloud Sun", Icon: CloudSun },
  { value: "moon", label: "Moon", Icon: Moon },
  { value: "star", label: "Star", Icon: Star, aliases: ["crown"] },
  { value: "cloud", label: "Cloud", Icon: Cloud },
  { value: "leaf", label: "Leaf", Icon: Leaf },
  { value: "cloud-rain", label: "Cloud Rain", Icon: CloudRain },

  { value: "house", label: "House", Icon: House, aliases: ["home"] },
  { value: "briefcase-business", label: "Briefcase", Icon: BriefcaseBusiness, aliases: ["work", "briefcase"] },
  { value: "shopping-cart", label: "Cart", Icon: ShoppingCart, aliases: ["shopping"] },
  { value: "bike", label: "Bike", Icon: Bike },
  { value: "coins", label: "Coins", Icon: Coins },
  { value: "user-round", label: "User", Icon: UserRound, aliases: ["user", "personal"] },
  { value: "backpack", label: "Backpack", Icon: Backpack, aliases: ["baggage-claim"] },
  { value: "graduation-cap", label: "Graduation Cap", Icon: GraduationCap, aliases: ["graduation", "school"] },

  { value: "umbrella", label: "Umbrella", Icon: Umbrella },
  { value: "shirt", label: "Shirt", Icon: Shirt },
  { value: "bath", label: "Bath", Icon: Bath },
  { value: "sofa", label: "Sofa", Icon: Sofa, aliases: ["armchair"] },
  { value: "bell", label: "Bell", Icon: Bell },
  { value: "zap", label: "Zap", Icon: Zap },
  { value: "image", label: "Image", Icon: Image },
  { value: "tree-pine", label: "Tree", Icon: TreePine, aliases: ["tree"] },

  { value: "ghost", label: "Ghost", Icon: Ghost },
  { value: "balloon", label: "Balloon", Icon: Balloon },
  { value: "palette", label: "Palette", Icon: Palette },
  { value: "badge-plus", label: "Badge", Icon: BadgePlus },
  { value: "gamepad-2", label: "Gamepad", Icon: Gamepad2, aliases: ["gamepad"] },
  { value: "life-buoy", label: "Lifebuoy", Icon: LifeBuoy },
  { value: "tv", label: "TV", Icon: Tv, aliases: ["monitor"] },
  { value: "music", label: "Music", Icon: Music },

  { value: "music-2", label: "Music Alt", Icon: Music2 },
  { value: "wine", label: "Wine", Icon: Wine },
  { value: "utensils", label: "Utensils", Icon: Utensils },
  { value: "cake-slice", label: "Cake", Icon: CakeSlice, aliases: ["cake"] },
  { value: "soup", label: "Soup", Icon: Soup },
  { value: "headphones", label: "Headphones", Icon: Headphones },
  { value: "library-big", label: "Library", Icon: LibraryBig, aliases: ["library"] },
  { value: "radio", label: "Radio", Icon: Radio },

  { value: "megaphone", label: "Megaphone", Icon: Megaphone, aliases: ["speaker"] },
  { value: "alarm-clock", label: "Alarm", Icon: AlarmClock, aliases: ["alarm"] },
  { value: "camera", label: "Camera", Icon: Camera, aliases: ["video"] },
  { value: "monitor", label: "Monitor", Icon: Monitor },
  { value: "video", label: "Video", Icon: Video },
  { value: "speaker", label: "Speaker", Icon: Speaker },
  { value: "heart", label: "Heart", Icon: Heart },
  { value: "sparkles", label: "Sparkles", Icon: Sparkles },

  { value: "flame", label: "Flame", Icon: Flame },
  { value: "building-2", label: "Building", Icon: Building2, aliases: ["building"] },
  { value: "church", label: "Church", Icon: Church },
  { value: "school", label: "School", Icon: School, aliases: ["schoolhouse"] },
  { value: "hotel", label: "Hotel", Icon: Hotel },
  { value: "store", label: "Store", Icon: Store },
  { value: "tent", label: "Tent", Icon: Tent },
  { value: "train-front", label: "Train", Icon: TrainFront, aliases: ["train"] },

  { value: "tram-front", label: "Tram", Icon: TramFront, aliases: ["tram"] },
  { value: "bus-front", label: "Bus", Icon: BusFront, aliases: ["bus"] },
  { value: "car-front", label: "Car", Icon: CarFront, aliases: ["car"] },
  { value: "ambulance", label: "Ambulance", Icon: Ambulance },
  { value: "truck", label: "Truck", Icon: Truck },
  { value: "plane", label: "Plane", Icon: Plane },
  { value: "rocket", label: "Rocket", Icon: Rocket },
  { value: "flask-conical", label: "Flask", Icon: FlaskConical, aliases: ["flask", "flask-2"] },

  { value: "syringe", label: "Syringe", Icon: Syringe },
  { value: "pill", label: "Pill", Icon: Pill },
  { value: "stethoscope", label: "Stethoscope", Icon: Stethoscope },
  { value: "briefcase-medical", label: "Medical", Icon: BriefcaseMedical },
  { value: "globe", label: "Globe", Icon: Globe },
  { value: "watch", label: "Watch", Icon: Watch },
  { value: "wrench", label: "Wrench", Icon: Wrench },
  { value: "calendar-days", label: "Calendar", Icon: CalendarDays, aliases: ["calendar"] },

  { value: "shopping-bag", label: "Shopping Bag", Icon: ShoppingBag },
  { value: "package", label: "Package", Icon: Package },
  { value: "bell-ring", label: "Bell Ring", Icon: BellRing },
  { value: "moon-star", label: "Moon Star", Icon: MoonStar },
  { value: "mic-2", label: "Microphone", Icon: Mic2 },
  { value: "waves", label: "Waves", Icon: Waves },
  { value: "scissors", label: "Scissors", Icon: Scissors },
  { value: "trash-2", label: "Trash", Icon: Trash2 },

  { value: "compass", label: "Compass", Icon: Compass },
  { value: "file-text", label: "File", Icon: FileText, aliases: ["file"] },
  { value: "clipboard", label: "Clipboard", Icon: Clipboard },
  { value: "mail", label: "Mail", Icon: Mail },
  { value: "trophy", label: "Trophy", Icon: Trophy },

  // Legacy-only mappings kept so existing saved bricks still render.
  { value: "gift", label: "Gift", Icon: Gift, legacyOnly: true },
  { value: "dumbbell", label: "Dumbbell", Icon: Dumbbell, aliases: ["gym", "sport"], legacyOnly: true },
  { value: "list-todo", label: "Todo", Icon: ListTodo, legacyOnly: true },
  { value: "handbag", label: "Handbag", Icon: Handbag, legacyOnly: true },
  { value: "wallet", label: "Wallet", Icon: Wallet, legacyOnly: true },
  { value: "badge-check", label: "Badge Check", Icon: BadgeCheck, aliases: ["badge", "smile"], legacyOnly: true },
  { value: "armchair", label: "Armchair", Icon: Armchair, legacyOnly: true },
];

export const brickIconMap: Record<string, LucideIcon> = brickIconEntries.reduce(
  (accumulator, entry) => {
    accumulator[entry.value] = entry.Icon;
    entry.aliases?.forEach((alias) => {
      accumulator[alias] = entry.Icon;
    });
    return accumulator;
  },
  {} as Record<string, LucideIcon>,
);

export const brickIconOptions: Array<{
  value: string;
  label: string;
  Icon: LucideIcon;
}> = brickIconEntries
  .filter((entry) => !entry.legacyOnly)
  .map(({ value, label, Icon }) => ({
    value,
    label,
    Icon,
  }));
