export const queryKeys = {
  profile: ["profile"] as const,
  bricks: ["bricks"] as const,
  brick: (id: string) => ["brick", id] as const,
  myBrickInvitations: ["my-brick-invitations"] as const,
  myCategoryInvitations: ["my-category-invitations"] as const,
  categories: ["categories"] as const,
  category: (id: string) => ["category", id] as const,
  categoryItems: (categoryId: string) => ["category-items", categoryId] as const,
  categoriesWithItems: ["categories-with-items"] as const,
  scheduledTodos: (params: Record<string, string | number | undefined>) => ["scheduled-todos", params] as const,
  events: (params: Record<string, string | number | undefined>) => ["events", params] as const,
  event: (id: string) => ["event", id] as const,
  eventTodos: (eventId: string) => ["event-todos", eventId] as const,
  jamMessages: (eventId: string) => ["jam-messages", eventId] as const,
  feedbacks: ["feedbacks"] as const,
  userSearch: (query: string) => ["user-search", query] as const,
  notifications: ["notifications"] as const,
  googleCalendarStatus: ["google-calendar-status"] as const,
};
